server:
  port: 8081
  servlet:
    context-path: /app

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/post?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${SIGNED_KEY:4FUNMjFiPr1J29IIqbjc7QbPpX2RPfQSVAH8b5dQHVK5XxyTdjC6Ax9DG8YodTb5}